title: Naming is hard
description: Thoughts from a web ops engineer
meta_description: "Tech notes from a web operations engineer"

exclude:
  - /404.md

markdown: kramdown
paginate: 5
tz: Europe/London
permalink: /:year/:month/:day/:title/

url: 'http://tech.mattbostock.com'
author: 'Matt Bostock'
email: 'matt@mattbostock.com'

google_analytics:
animated: false

gems:
  - jekyll-mentions
