name: Naming is hard
description: Thoughts from a web ops engineer
meta_description: "Tech notes from a web operations engineer"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
